openapi: 3.1.0
info:
  title: todo-app API
  description: |-
    ## 概要
    - todo-appのAPI仕様書
servers:
  - url: http://localhost:8083
    description: ローカル開発環境
tags:
  - name: boards
    description: ボード関連エンドポイント
  - name: categories
    description: カテゴリ関連エンドポイント
  - name: items
    description: アイテム関連エンドポイント
paths:
  /boards:
    get:
      summary: ボード一覧を取得するエンドポイント
      description: |-
        ## 概要
        - ボード一覧を取得する
      tags:
        - boards
      operationId: getBoards
      security: []
      responses:
        "200":
          description: 全てのボードを返す
          content:
            application/json:
              schema:
                $ref: "./responses/boards.yml"
        default:
          $ref: "./errors/unexpected.yml"
    post:
      summary: ボードを新規作成するエンドポイント
      description: |-
        ## 概要
        - ボードのタイトルを受け取り、新規作成したボード情報を返す
      tags:
        - boards
      operationId: createBoard
      security: []
      requestBody:
        description: 新規作成するボード
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                board_title:
                  type: string
                  description: 新規作成するボードのタイトル
                  example: UTTC
              required:
                - board_title
      responses:
        "201":
          description: Successfully create a new board
          content:
            application/json:
              schema:
                $ref: "./responses/board.yml"
        default:
          $ref: "./errors/unexpected.yml"
  /boards/{board_id}:
    post:
      summary: ボードタイトルを更新するエンドポイント
      description: |-
        ## 概要
        - ボードのタイトルを受け取り、更新したボード情報を返す
      tags:
        - boards
      operationId: updateBoard
      security: []
      parameters:
        - name: board_id
          in: path
          description: 更新するボードのID
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        description: 更新するボード
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                board_title:
                  type: string
                  description: 更新するボードのタイトル
                  example: UTTC
              required:
                - board_title
      responses:
        "200":
          description: Successfully update a board
          content:
            application/json:
              schema:
                $ref: "./responses/board.yml"
        default:
          $ref: "./errors/unexpected.yml"
    delete:
      summary: ボードを削除するエンドポイント
      description: |-
        ## 概要
        - ボードIDを受け取り、ボードを削除する
      tags:
        - boards
      operationId: deleteBoard
      security: []
      parameters:
        - name: board_id
          in: path
          description: 削除するボードのID
          required: true
          schema:
            type: integer
            example: 1
      responses:
        "204":
          description: Successfully delete a board
        default:
          $ref: "./errors/unexpected.yml"
  /categories:
    get:
      summary: 特定のボード内のカテゴリ一覧を取得するエンドポイント
      description: |-
        ## 概要
        - 特定のボード内のカテゴリ一覧を取得する
      tags:
        - categories
      operationId: getCategories
      security: []
      parameters:
        - name: board_id
          in: query
          description: カテゴリ一覧を取得するボードのIDをクエリパラメータで指定
          required: true
          schema:
            type: integer
            example: 1
      responses:
        "200":
          description: 特定のボード内のカテゴリを全て返す
          content:
            application/json:
              schema:
                $ref: "./responses/categories.yml"
        default:
          $ref: "./errors/unexpected.yml"
    post:
      summary: カテゴリを新規作成するエンドポイント
      description: |-
        ## 概要
        - カテゴリのタイトルを受け取り、新規作成したカテゴリ情報を返す
      tags:
        - categories
      operationId: createCategories
      security: []
      parameters:
        - name: board_id
          in: query
          description: カテゴリ一覧を取得するボードのID
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        description: 新規作成するカテゴリ
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                board_id:
                  type: integer
                  description: 新規作成するカテゴリのボードID
                  example: 1
                category_title:
                  type: string
                  description: 新規作成するカテゴリのタイトル
                  example: TODO
              required:
                - board_id
                - category_title
      responses:
        "201":
          description: Successfully create a new category
          content:
            application/json:
              schema:
                $ref: "./entity/category.yml"
        default:
          $ref: "./errors/unexpected.yml"
  /categories/{category_id}:
    post:
      summary: カテゴリタイトルを更新するエンドポイント
      description: |-
        ## 概要
        - カテゴリのタイトルを受け取り、更新したカテゴリ情報を返す
      tags:
        - categories
      operationId: updateCategory
      security: []
      parameters:
        - name: category_id
          in: path
          description: 更新するカテゴリのID
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        description: 更新するカテゴリ
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category_title:
                  type: string
                  description: 更新するカテゴリのタイトル
                  example: TODO
              required:
                - category_title
      responses:
        "200":
          description: Successfully update a category
          content:
            application/json:
              schema:
                $ref: "./entity/category.yml"
        default:
          $ref: "./errors/unexpected.yml"
    delete:
      summary: カテゴリを削除するエンドポイント
      description: |-
        ## 概要
        - カテゴリIDを受け取り、カテゴリを削除する
      tags:
        - categories
      operationId: deleteCategory
      security: []
      parameters:
        - name: category_id
          in: path
          description: 削除するカテゴリのID
          required: true
          schema:
            type: integer
            example: 1
      responses:
        "204":
          description: Successfully delete a category
        default:
          $ref: "./errors/unexpected.yml"
  /items:
    get:
      summary: カテゴリ内のアイテム一覧を取得するエンドポイント
      description: |-
        ## 概要
        - 特定のカテゴリ内のアイテム一覧を取得する
      tags:
        - items
      operationId: getItems
      security: []
      parameters:
        - name: category_id
          in: query
          description: アイテム一覧を取得するカテゴリのIDをクエリパラメータで指定
          required: true
          schema:
            type: integer
            example: 1
      responses:
        "200":
          description: 特定のカテゴリ内のアイテムを全て返す
          content:
            application/json:
              schema:
                $ref: "./responses/items.yml"
        default:
          $ref: "./errors/unexpected.yml"
    post:
      summary: アイテムを新規作成するエンドポイント
      description: |-
        ## 概要
        - 新規のアイテム情報を受け取り、新規作成したアイテム情報を返す
      tags:
        - items
      operationId: createItem
      security: []
      parameters:
        - name: category_id
          in: query
          description: 新規作成するアイテムのカテゴリID
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        description: 新規作成するアイテム
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                board_id:
                  type: integer
                  description: 新規作成するアイテムのボードID
                  example: 1
                list_id:
                  type: integer
                  description: 新規作成するアイテムのリストID
                  example: 1
                item_title:
                  type: string
                  description: 新規作成するアイテムのタイトル
                  example: TODO
                content:
                  type: string
                  description: 新規作成するアイテムの内容
                  example: "TODOの内容"
                expired_at:
                  type: string
                  description: 新規作成するアイテムの期限
                  format: date-time
                  example: "2021-01-01 00:00:00"
              required:
                - board_id
                - list_id
                - item_title
                - content
                - expired_at
      responses:
        "201":
          description: Successfully create a new item
          content:
            application/json:
              schema:
                $ref: "./entity/item.yml"
        default:
          $ref: "./errors/unexpected.yml"
  /items/{item_id}:
    put:
      summary: アイテム情報を更新するエンドポイント
      description: |-
        ## 概要
        - アイテム情報を受け取り、更新したアイテム情報を返す
      tags:
        - items
      operationId: updateItem
      security: []
      parameters:
        - name: item_id
          in: path
          description: 更新するアイテムのID
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        description: 更新するアイテム
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                item_title:
                  type: string
                  description: 更新するアイテムのタイトル
                  example: TODO
                content:
                  type: string
                  description: 更新するアイテムの内容
                  example: "TODOの内容"
                expired_at:
                  type: string
                  description: 更新するアイテムの期限
                  format: date-time
                  example: "2021-01-01 00:00:00"
              required:
                - item_title
                - content
                - expired_at
      responses:
        "200":
          description: Successfully update an item
          content:
            application/json:
              schema:
                $ref: "./entity/item.yml"
        default:
          $ref: "./errors/unexpected.yml"
    post:
      summary: アイテムをアーカイブするエンドポイント
      description: |-
        ## 概要
        - アイテムIDを受け取り、アイテムをアーカイブする
      tags:
        - items
      operationId: archiveItem
      security: []
      parameters:
        - name: item_id
          in: path
          description: アーカイブするアイテムのID
          required: true
          schema:
            type: integer
            example: 1
      responses:
        "204":
          description: Successfully archive an item
        default:
          $ref: "./errors/unexpected.yml"
  /items/archived:
    get:
      summary: ボード内のアーカイブ済みアイテム一覧を取得するエンドポイント
      description: |-
        ## 概要
        - 特定のボード内のアーカイブ済みアイテム一覧を取得する
      tags:
        - items
      operationId: getArchivedItems
      security: []
      paramter:
        - name: board_id
          in: query
          description: アーカイブ済みアイテム一覧を取得するボードのID
          required: true
          schema:
            type: integer
            example: 1
      responses:
        "200":
          description: 特定のボード内のアーカイブ済みアイテムを全て返す
          content:
            application/json:
              schema:
                $ref: "./responses/items.yml"
        default:
          $ref: "./errors/unexpected.yml"
  /items/archived/{item_id}:
    post:
      summary: アイテムをアーカイブ解除するエンドポイント
      description: |-
        ## 概要
        - アイテムIDを受け取り、アイテムをアーカイブ解除する
      tags:
        - items
      operationId: unarchiveItem
      security: []
      parameters:
        - name: item_id
          in: path
          description: アーカイブ解除するアイテムのID
          required: true
          schema:
            type: integer
            example: 1
      responses:
        "204":
          description: Successfully unarchive an item
        default:
          $ref: "./errors/unexpected.yml"
