openapi: 3.1.0
info:
  title: todo-app API
  description: |-
    ## 概要
    - todo-appのAPI仕様書
servers:
  - url: http://localhost:3030
    description: ローカル開発環境
tags:
  - name: healthcheck
    description: 疎通確認エンドポイント
  - name: boards
    description: ボード関連エンドポイント
  - name: lists
    description: リスト関連エンドポイント
  - name: items
    description: アイテム関連エンドポイント
paths:
  /health:
    get:
      summary: 疎通確認用エンドポイント
      description: |-
        ## 概要
        - APIサーバーの疎通確認を行う
      tags:
        - healthcheck
      operationId: healthCheck
      security: []
      responses:
        "200":
          description: Successfully connected
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/health_check"
        default:
          $ref: "#/components/responses/error_unexpected"
  /boards:
    get:
      summary: ボード一覧を取得するエンドポイント
      description: |-
        ## 概要
        - ボード一覧を取得する
      tags:
        - boards
      operationId: getBoards
      security: []
      responses:
        "200":
          description: ボード一覧のリストを返す
          content:
            application/json:
              schema:
                $ref: "./responses/boards.yml"
        default:
          $ref: "./errors/unexpected.yml"
  /lists:
    get:
      summary: リスト一覧を取得するエンドポイント
      description: |-
        ## 概要
        - リスト一覧を取得する
      tags:
        - lists
      operationId: getLists
      security: []
      responses:
        "200":
          description: リスト一覧のリストを返す
          content:
            application/json:
              schema:
                $ref: "./responses/lists.yml"
        default:
          $ref: "./errors/unexpected.yml"
  /items:
    get:
      summary: アイテム一覧を取得するエンドポイント
      description: |-
        ## 概要
        - アイテム一覧を取得する
      tags:
        - items
      operationId: getItems
      security: []
      responses:
        "200":
          description: アイテム一覧のリストを返す
          content:
            application/json:
              schema:
                $ref: "./responses/items.yml"
        default:
          $ref: "./errors/unexpected.yml"
