version: "3.1"

services:
  db:
    container_name: todo-mysql
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      TZ: Asia/Tokyo
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - type: volume
        source: todo-app-db
        target: /var/lib/mysql
        volume:
          nocopy: true
  swagger-ui:
    container_name: todo-swagger
    image: swaggerapi/swagger-ui
    ports:
      - 8082:8080
    environment:
      SWAGGER_JSON: /oapi/api.yml
    volumes:
      - ./oapi:/oapi

volumes:
  todo-app-db:
